name: Build

on:
  push:
    branches:
      - "**"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Use PNPM
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 9.0.0

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install
        run: pnpm install

      - name: Build for production
        run: pnpm build
